# Generated by Django 3.2.9 on 2021-11-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('description', models.TextField(verbose_name='Book Description')),
                ('release_date', models.DateField(verbose_name='Release Data')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'db_table': 'books',
            },
        ),
    ]
